<script lang="ts">
	import AutoHtmHeader from '$lib/components/AutoHTMHeader.svelte';
	import MarkdownParser from '$lib/components/MDParser/MarkdownParser.svelte';

	const postMeta = {
		title: 'Privacy, License, and Copyright',
		author: 'Eli Bukoski',
		description:
			'Privacy expectations, licensing terms, copyright terms, post-authenticity notes, and ownership notes for Bukoski.dev and its hosted tools.',
		tags: [
			'privacy',
			'license',
			'copyright',
			'mit',
			'all-rights-reserved',
			'tools',
			'local-use',
			'authenticity',
			'sponsorship'
		]
	};

	const markdownContent = [
		'# Privacy, License, and Copyright',
		'',
		'_Last updated: 2026-06-30_',
		'',
		'This page covers privacy expectations for the hosted website, licensing for the website and tool code, copyright treatment for posts and media, post-authenticity disclosures, and ownership of work entered into the tools.',
		'',
		'## Plain-English Summary',
		'',
		'**Use the hosted site as if anything you enter could become public.**',
		'',
		'- Do not enter passwords, API keys, personal identifiers, customer data, trade secrets, or other confidential material into the hosted site.',
		'- Shared links are obviously public, but even without using a share feature you should assume there is no expectation of privacy on the hosted site.',
		'- If privacy matters, run the tools locally on your own machine.',
		'- Any project data or other work product that you enter into a tool remains yours.',
		'- The website code and tool code are MIT licensed.',
		'- Posts, written content, images, graphics, and videos are all rights reserved unless a specific page says otherwise.',
		'- Posts are unsponsored unless the post explicitly says otherwise, and any sponsorship will be disclosed on that post including what was provided and any conditions attached.',
		'',
		'## Privacy and Hosted Use',
		'',
		'This website is a public portfolio and tool host. It is not offered as a confidential workspace, secure file vault, or private collaboration service.',
		'',
		'Anything submitted to the hosted site should be treated as non-confidential. That includes text, uploaded material, imported project state, schematics, settings, design notes, generated links, and similar tool data.',
		'',
		'That does not mean the site claims ownership of your input. It means you should not rely on the hosted deployment to keep that input private.',
		'',
		'## Share Features and Persistence',
		'',
		'Share features exist to make tool output portable, not private.',
		'',
		'Even when you do not intentionally publish a share link, the safe assumption is still that information entered into the hosted website has no privacy guarantee. Logs, caches, stored state, browser history, copied URLs, or future changes to site behavior can all make hosted use unsuitable for sensitive material.',
		'',
		'If you are working with proprietary, regulated, customer, or otherwise sensitive information, run the tool locally instead of using the hosted copy.',
		'',
		'## Ownership of Tool Input',
		'',
		'Design files, parameters, notes, and other work product that you enter into a tool remain your work. Using the website does not transfer ownership of that material to the website owner.',
		'',
		'Ownership and privacy are separate issues. Your work can still be yours while the hosted site remains a poor place for confidential use.',
		'',
		'## Post Authenticity and Sponsorship',
		'',
		'Unless a post explicitly says otherwise, it is entirely unsponsored and financed only by me.',
		'',
		'If a post or project is sponsored, that specific post will disclose the sponsorship directly on the page.',
		'',
		'That disclosure will include the nature of the sponsorship, including what was provided to me and any conditions, restrictions, or expectations attached to it.',
		'',
		'If there is no sponsorship disclosure on a post, you should read that post as independent and self-funded.',
		'',
		'## Software License',
		'',
		'The website code and the interactive tool code are licensed under the MIT License.',
		'',
		'That means you may use, copy, modify, merge, publish, distribute, sublicense, and sell the software under the MIT terms, provided the required copyright and license notice are preserved.',
		'',
		'This extends to the tools provided on this site, and any files, scripts, or other downloads (located within the `/downloads` route) that are part of the website or tool codebase.',
		'',
		'## Content Copyright',
		'',
		'Unless a specific page, or media content says otherwise, the following website content is all rights reserved:',
		'',
		'- Posts and written page content',
		'- Images, diagrams, graphics (excluding tools), and screenshots',
		'- Video and motion content',
		'- Other portfolio media and presentation assets',
		'',
		'Do not copy, mirror, republish, redistribute, train on, or reuse that content without explicit written permission.',
		'',
		'## Repository Split',
		'',
		'In the repository, the software license is described in LICENSE and the content restrictions are described in CONTENT-LICENSE.',
		'',
		'If a specific file, download, or project page states different terms, that more specific notice controls for that item.',
		'',
		'## Contact and Permission',
		'',
		'If you want to reuse software from this project, follow the MIT License terms.',
		'',
		'If you want to reuse posts, images, videos, or other portfolio content, request permission first (email eli@bukoski.dev).'
	].join('\n');
</script>

<AutoHtmHeader {postMeta} />

<MarkdownParser markdownString={markdownContent} />
